GET http://localhost:3003/api/blogs
###

POST http://localhost:3003/api/blogs
Content-Type: application/json

# {
#     "title": "code with Aga",
#     "author": "Agnieszka Kosiedowska",
#     "url": "www.codewithaga",
#     "likes": "5"
# }

# {
#     "title": "sewing blog",
#     "author": "Agnieszka Kosiedowska",
#     "url": "www.sew.com",
#     "likes": "7"
# }

# {
#     "title": "frontend blog",
#     "author": "Agnieszka Kosiedowska",
#     "url": "www.front.com",
#     "likes": "34"
# }

{
    "title": "learn piano blog",
    "author": "Piotr K",
    "url": "www.piano.blogspot.com",
    "likes": "100"
}

###

DELETE  http://localhost:3003/api/blogs/650c6cd0ee49c8002bd2f740

###

PUT http://localhost:3003/api/blogs/65004b01d396c4cbebf5bc71
Content-Type: application/json

 {
    "title": "code with Aga",
    "author": "Agnieszka Kosiedowska",
    "url": "www.codewithaga",
    "likes": "99",
    "id": "65004b01d396c4cbebf5bc71"
  }